
static const cMenu::icons_et cMenu::menuIcons[menuItemEnd] PROGMEM ={
																iconMenu,		// // Leve 0	
																iconSmoke,		// menuItemSmoke,		
																iconSettings,	// menuItemSettings,
																iconInfo,		// menuItemInfo,
																				// // level 2 - menuItemSettings
																iconMode,		// menuItemMode,		
																iconHeat,		// menuItemHeat,
																iconAir,		// menuItemAir,
																iconBattery,	// menuItemBattery,
																iconReset,		// menuItemReset,		
																				// // level 3 - menuItemMode
																iconDutyCycle,	// menuItemDutyCycle,	
																iconPeriod,		// menuItemPeriod,
																iconSequence,	// menuItemSequence,
																				// // level 3 - menuItemHeat
																iconLimitHigh,		// menuItemHeatLimit,
																iconHeatStart,	// menuItemHeatStart,
																iconHeatSmoke,	// menuItemHeatSmokePower,
																iconHeatHold,	// menuItemHeatHold,
																				// // level 3 - menuItemAir
																iconLimitHigh,		// menuItemAirLimit,
																iconAirStart,	// menuItemAirStart,
																iconAirSmoke,	// menuItemAirSmokePower,
																iconAirHold,	// menuItemAirHold,
																				// // level 3 - menuItemBattery,
																iconLimitLow,	// menuItemBatteryLimit,
																iconInfo,		// menuItemBatteryInfo,
																				// // level 4 - menuItemHeatStart
																iconDelay,		// menuItemHeatStartDelay,		
																iconPower,		// menuItemHeatStartPower,
																iconDuration,	// menuItemHeatStartDuration,
																				// // level 4 - menuItemHeatHold
																iconPower,		// menuItemHeatHoldPower, 
																iconDuration,	// menuItemHeatHoldDuration,
																				// // level 4 - menuItemAirStart
																iconDelay,		// menuItemAirStartDelay,
																iconPower,		// menuItemAirStartPower,	
																iconDuration,	// menuItemAirStartDuration,
																// // level 4 - menuItemAirHold
																iconPower,		// menuItemAirHoldPower,
																iconDuration,	// menuItemAirHoldDuration,
																// menuItemBatteryLow
																iconBatteryLow
															};
															
static const cMenu::menuItem_et cMenu::menuList[] PROGMEM = {
																menuItemMain, 
																	menuItemSmoke, 
																	menuItemSettings, 
																	menuItemInfo, 
																	menuItemEnd,
																menuItemSmoke,
																	menuItemProcess,
																	menuItemEnd,
																menuItemSettings,
																	menuItemMode,
																	menuItemHeat,
																	menuItemAir,
																	menuItemBattery,
																	menuItemReset,
																	menuItemEnd,
																menuItemInfo,
																	menuItemProcess,
																	menuItemEnd,
																menuItemMode,
																	menuItemDutyCycle,
																	menuItemPeriod,
																	menuItemSequence,
																	menuItemEnd,
																menuItemHeat,
																	menuItemHeatLimit,
																	menuItemHeatStart,
																	menuItemHeatSmokePower,
																	menuItemHeatHold,
																	menuItemEnd,
																menuItemAir,
																	menuItemAirLimit,
																	menuItemAirStart,
																	menuItemAirSmokePower,
																	menuItemAirHold,
																	menuItemEnd,
																menuItemBattery,
																	menuItemBatteryLimit,
																	menuItemBatteryInfo,
																	menuItemEnd,
																menuItemReset,
																	menuItemConfirm,
																	menuItemEnd,
																menuItemDutyCycle,
																	menuItemEdit,
																	menuItemEnd,
																menuItemPeriod,
																	menuItemEdit,
																	menuItemEnd,
																menuItemSequence,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatLimit,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatStart,
																	menuItemHeatStartDelay,
																	menuItemHeatStartPower,
																	menuItemHeatStartDuration,
																	menuItemEnd,
																menuItemHeatSmokePower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatHold,
																	menuItemHeatHoldPower,
																	menuItemHeatHoldDuration,
																	menuItemEnd,																	
																menuItemAirLimit,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirStart,
																	menuItemAirStartDelay,
																	menuItemAirStartPower,
																	menuItemAirStartDuration,
																	menuItemEnd,
																menuItemAirSmokePower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirHold,
																	menuItemAirHoldPower,
																	menuItemAirHoldDuration,
																	menuItemEnd,
																menuItemHeatStartDelay,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatStartPower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatStartDuration,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatHoldDuration,
																	menuItemEdit,
																	menuItemEnd,
																menuItemHeatHoldPower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirStartDelay,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirStartPower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirStartDuration,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirHoldDuration,
																	menuItemEdit,
																	menuItemEnd,
																menuItemAirHoldPower,
																	menuItemEdit,
																	menuItemEnd,
																menuItemBatteryLimit,
																	menuItemEdit,
																	menuItemEnd,
																menuItemBatteryInfo,
																	menuItemData,
																	menuItemEnd,
																menuItemBatteryLow,
																	menuItemData,
																	menuItemEnd,
																menuItemEnd
																
															};

static const cMenu::menuItem_et cMenu::menuBack[menuItemEnd] PROGMEM ={
																menuItemMain,		// // Leve 0	
																menuItemMain,		// menuItemSmoke,		
																menuItemMain,		// menuItemSettings,
																menuItemMain,		// menuItemInfo,
																// // level 2 - menuItemSettings
																menuItemSettings,	// menuItemMode,		
																menuItemSettings,	// menuItemHeat,
																menuItemSettings,	// menuItemAir,
																menuItemSettings,	// menuItemBattery,		
																menuItemSettings,	// menuItemReset,		
																// // level 3 - menuItemMode
																menuItemMode,		// menuItemDutyCycle,	
																menuItemMode,		// menuItemPeriod,
																menuItemMode,		// menuItemSequence,
																// // level 3 - menuItemHeat
																menuItemHeat,		// menuItemHeatLimit,
																menuItemHeat,		// menuItemHeatStart,
																menuItemHeat,		// menuItemHeatSmokePower,
																menuItemHeat,		// menuItemHeatHold,
																// // level 3 - menuItemAir
																menuItemAir,		// menuItemAirLimit,
																menuItemAir,		// menuItemAirStart,
																menuItemAir,		// menuItemAirSmokePower,
																menuItemAir,		// menuItemAirHold,
																// // level 3 - menuItemBattery
																menuItemBattery,	// menuItemBatteryLimit,
																menuItemBattery,	// menuItemBatteryInfo,
																// // level 4 - menuItemHeatStart
																menuItemHeatStart,	// menuItemHeatStartDelay,		
																menuItemHeatStart,	// menuItemHeatStartPower,
																menuItemHeatStart,	// menuItemHeatStartDuration,
																// // level 4 - menuItemHeatHold
																menuItemHeatHold,	// menuItemHeatHoldPower, 
																menuItemHeatHold,	// menuItemHeatHoldDuration,
																// // level 4 - menuItemAirStart
																menuItemAirStart,	// menuItemAirStartDelay,
																menuItemAirStart,	// menuItemAirStartPower,	
																menuItemAirStart,	// menuItemAirStartDuration,
																// // level 4 - menuItemAirHold
																menuItemAirHold,	// menuItemAirHoldPower,
																menuItemAirHold,	// menuItemAirHoldDuration,
																// Battery low display
																menuItemBattery
															};


static const cMenu::val_st cMenu::menuVals[] PROGMEM = {
															{	menuItemDutyCycle,
																cParameter::valID_dutyCycle,
																3,
																unit_percent },
															{	menuItemPeriod,
																cParameter::valID_periode,
																5,
																unit_ms },
															{	menuItemSequence,		
																cParameter::valID_sequence,
																2,
																unit_none },
															{	menuItemHeatLimit,
																cParameter::valID_heatLimit,
																4,
																unit_mV },
															{	menuItemHeatStartDelay,
																cParameter::valID_heatStartDelay,
																3,
																unit_ms },
															{	menuItemHeatStartPower,
																cParameter::valID_heatStartPower,	
																3,
																unit_percent },
															{	menuItemHeatStartDuration,
																cParameter::valID_heatStartDuration,
																3,
																unit_ms },
															{	menuItemHeatSmokePower,
																cParameter::valID_heatSmokePower,	
																3,
																unit_percent },
															{	menuItemHeatHoldPower,
																cParameter::valID_heatHoldPower,
																3,
																unit_percent },
															{	menuItemHeatHoldDuration,
																cParameter::valID_heatHoldDuration,	
																3,
																unit_ms },
															{	menuItemAirLimit,
																cParameter::valID_airLimit,	
																4,
																unit_mV },
															{	menuItemAirStartDelay,
																cParameter::valID_airStartDelay,	
																3,
																unit_ms },
															{	menuItemAirStartPower,
																cParameter::valID_airStartPower,	
																3,
																unit_percent },
															{	menuItemAirStartDuration,
																cParameter::valID_airStartDuration,	
																3,
																unit_ms },
															{	menuItemAirSmokePower,
																cParameter::valID_airSmokePower,
																3,
																unit_percent },
															{	menuItemAirHoldPower,
																cParameter::valID_airHoldPower,	
																3,
																unit_percent },
															{	menuItemAirHoldDuration,
																cParameter::valID_airHoldDuration,	
																3,
																unit_ms},
															{	menuItemBatteryLimit,
																cParameter::valID_batteryLimit,	
																5,
																unit_mV},
															{	menuItemBatteryInfo,
																cParameter::valID_end,
																5,
																unit_mV},
															{	menuItemBatteryLow,
																cParameter::valID_end,
																5,
																unit_mV},
															{	menuItemEnd,
																cParameter::valID_end,
																0,
																unit_none }
														};
